### ISSUE TITLE
Please support the color() function in CSS Color Module 4

### ISSUE THREAD

**Issue by sphinxrave** [wangyunduo/vscode-ext-color-highlight#2]
Thank you for maintaining the color highlight extension and extending it with CSS Color Module 4 features! It's really helpful.

However, I installed it and it doesn't seem to support the `color()` function:
https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/color

```css
.box {
    background-color: color(display-p3 1 0.5 0);
    color: color(display-p3 1 0.5 0 / .5);
    background-color: color(srgb 0 0 1);
}
```
